# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: fabric-1.8.9 - Draft release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags: 'v*-1.8.9' # Push events to matching v*-1.8.9

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8 & 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: |
          8
          17
    - name: Install advancecomp
      run: sudo apt-get install advancecomp
    - name: Install strip-nondeterminism
      run: sudo apt-get install strip-nondeterminism
    - name: Build with Gradle
      env:
        BUILD_RELEASE: ${{ github.event.release.prerelease == false }}
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper
        cache-disabled: true
        arguments: build --stacktrace --warning-mode all
    - name: Run strip-nondeterminism on built .jar files
      run: strip-nondeterminism build/libs/*.jar
    - name: Run advzip (-i 99999) on built .jar files
      run: advzip --shrink-insane -kzi 99999 -p build/libs/*.jar
    - name: Draft release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref }}
        name: Draft release ${{ github.ref }}
        body: Replace this text with the description of this release!
        draft: true
        prerelease: false
        files: build/libs/*.jar
